### ISSUE TITLE
Mat and thorium smelters crash the game 

### ISSUE THREAD

**Issue by christyoleary** [Mesokrix/Vanilla-Upgraded#10]
Whenever I hook up oberald into a melter it crashes, as well as trying to make thorium. I am playing on Android so I can't give error code.

**Comment by Mesokrix** [comment]
What is your version of the mod ?

**Comment by christyoleary** [comment]
I'm using version 2.2.15

**Comment by Mesokrix** [comment]
So update, the official version is 2.2.20, if the problem is always here, say me please

**Comment by christyoleary** [comment]
Yes that fixed it, thank you very much I love the mod!

**Comment by Mesokrix** [comment]
You're welcome
