### ISSUE TITLE
The Reconstructor turret often blows up immediately after/while firing

### ISSUE THREAD

**Issue by akorn** [Mesokrix/Vanilla-Upgraded#16]
Even though it takes no enemy fire.

Is this intentional?

**Comment by akorn** [comment]
I observed it a little more closely. What happens is that it first rapidly loses cryofluid level (despite being fed by two gigantic liquid tanks, both full), then health.

It's as if firing uses too much cryofluid maybe?

**Comment by Mesokrix** [comment]
Hmm, i have do and redo the code of the turret, i think the problem come to mindustry v5. Maybe it's would be fix for the v6
