### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Lucas559-noob** [Mesokrix/Vanilla-Upgraded#2]
[crash-report-06_07_2020_20_22_59.txt](https://github.com/Mesokrix/Vanilla-Upgraded/files/4743441/crash-report-06_07_2020_20_22_59.txt)
Crash the game on loading

**Comment by Mesokrix** [comment]
Yeah i see the problem and i try to resolve it...

**Comment by Mesokrix** [comment]
the crashing problem once the download is resolved
