### ISSUE TITLE
Problemas con mod.json

### ISSUE THREAD

**Issue by TimmyTurner27** [Mesokrix/Vanilla-Upgraded#23]
Version: andriod
Otro problema: no hay posibilidad de minar el item "Overlord" en el juego ni una fabrica para su construcción, por lo tanto es inutíl el item y sus consiguientes "Obsidiana" y "Esmeralda". :(

**Comment by Pekka-Angelo** [comment]
Agregaremos un planeta para poder utilizar estos recursos

**Comment by Mesokrix** [comment]
Emerald and obsidian can't be mined for the moment, we planned to add oberald on new planet
