### ISSUE TITLE
Wall Prices are unbalanced

### ISSUE THREAD

**Issue by Essnato** [Mesokrix/Vanilla-Upgraded#24]
I think the construction cost of walls is way too high, for example a 1x1 copper wall costs 6 copper, and a 2x2 copper wall costs 24, which makes sense as it is 4 times more wall than the last, so it costs 4x more. However the Huge copper wall from this mod costs 145 copper to build, which is significantly more than what it should be, which is 6*9=63 copper for it to be balanced, same for the 4x4 wall which costs 245 as opposed to 16*6=96 copper. This makes it so there is no reason to build the large walls so they never get used. I would appreciate if this problem would be fixed.

**Comment by Pekka-Angelo** [comment]
I will fix this price problem right from the wall
