### ISSUE TITLE
Spund .ine

### ISSUE THREAD

**Issue by mockwriter7772** [Mesokrix/Vanilla-Upgraded#25]
When i place sound mine the game IMMEDIATELY crashes =/

**Comment by Pekka-Angelo** [comment]
We temporarily removed it from the Mods to resolve the issue.
You have to reload your Mods!

**Comment by mockwriter7772** [comment]
Forgive my spelling tho

**Comment by Pekka-Angelo** [comment]
No problem

**Comment by Pekka-Angelo** [comment]
Fix
