### ISSUE TITLE
Please describe what the mod gives

### ISSUE THREAD

**Issue by psqq** [Mesokrix/Vanilla-Upgraded#3]
What content, enemies, objects, buildings, locations.

**Comment by Mesokrix** [comment]
in readme.md ? or mod.json ?

**Comment by psqq** [comment]
Is this a mod that brings the game back to old resources? In the readme.md and mod.json is not written not about one object that adds your mod. Does your mod add any objects to the game?

**Comment by Mesokrix** [comment]
No, i write where the what the mode gives ? in readme.md ? or in mod.json ?

**Comment by Mesokrix** [comment]
finally i write in readme.md
