### ISSUE TITLE
Cant add the mod

### ISSUE THREAD

**Issue by sandal455** [Mesokrix/Vanilla-Upgraded#31]
I cant import the mod from github, it says the mod cant be found

**Comment by jensholzberger** [comment]
Please look here: https://discord.com/channels/730535373306069114/764482282571431936/789438567616479252
for download instructions.

**Comment by Voz-Duh** [comment]
^

**Comment by star-krafter** [comment]
Reopen this due to the fact that the gradle.yml needs to be updated and so cannot be added
