### ISSUE TITLE
Vanilla-Upgraded

### ISSUE THREAD

**Issue by SkyViper208** [Mesokrix/Vanilla-Upgraded#39]

**Comment by Duvent-mindustry** [comment]
what is this issue, why must this exist, is there a reason?

**Comment by SkyViper208** [comment]
> what is this issue, why must this exist, is there a reason?

Ah sorry, I'm new to github and I'm just trying to download the thing. But the only button thst exists is the issue button and I was hoping that mightve done something. Also I'm on android
