### ISSUE TITLE
Volcano Broken

### ISSUE THREAD

**Issue by JoanJetson** [Mesokrix/Vanilla-Upgraded#5]
Volcano campaign map crashes game when running on v2.1.3 of Vanilla Upgraded running on Mindustry release build 104.4 on iPad OS 13.5.1.

Other campaign maps from mod work. Have tried disabling other mods, reloading mod, uninstalling and reinstalling mod, playing other levels then trying again. Primary problem is this is the only map to get certain resources to advance the tech tree. 

Crash happens during load of map.

**Comment by JoanJetson** [comment]
Just noticed changes committed in the last hour. 
Current errors for iOS for v2.2.1 are:
![10C4C295-FFC6-4CB5-8D97-7C2BFE84A4F5](https://user-images.githubusercontent.com/12766732/88305856-3bad6900-ccc7-11ea-89cd-cd70241318fb.png)
![DE5129F3-D47E-4532-8BC0-7B74172865D2](https://user-images.githubusercontent.com/12766732/88305869-410ab380-ccc7-11ea-8ba8-e8a1040f9ccb.png)

**Comment by Mesokrix** [comment]
for the map just update the mod, for other i don't know what u do but work for me so i can't do anithing.

**Comment by Mesokrix** [comment]
![Screenshot_2020-07-23-18-40-18](https://user-images.githubusercontent.com/64345010/88313607-0d09af80-cd14-11ea-8529-5b559ce1b304.png)
![Screenshot_2020-07-23-18-39-45](https://user-images.githubusercontent.com/64345010/88313624-11ce6380-cd14-11ea-9667-cf2bd4ce8c21.png)

**Comment by JoanJetson** [comment]
Thanks for confirming. I know iOS mod ding is unstable so no idea what might break the main build. I've been posting in the bugs channel in the discord.

Alright, so adding type to big heal and changing the research for sound mine to "shock-mine" resolved the iOS/iPadOS issues
Functioning fork is here: https://github.com/JoanJetson/Vanilla-Upgraded
Volcano still broken on iOS but will try to fix that on my fork.

**Comment by Mesokrix** [comment]
![Screenshot_2020-07-23-18-43-14](https://user-images.githubusercontent.com/64345010/88313898-75589100-cd14-11ea-8eaa-0c7f3d6fe869.png)

**Comment by Mesokrix** [comment]
Ok i can try to fix by an other method for ios

**Comment by JoanJetson** [comment]
To document the issue here as well, The msav appears to be broken for iOS. opening the editor shows OHNO for the preview. Opening it does provide an error log that doesn't allow me to copy the text.
![0B1E92E3-8E5F-4686-8E9B-8D4DE859766E](https://user-images.githubusercontent.com/12766732/88318379-e0d03d80-ccd7-11ea-8023-6e336eaa655c.jpeg)

**Comment by JoanJetson** [comment]
And trying to open Volcan in editor gives: 

![81FEA5D1-B21D-4D2C-9587-859A5ECB4D3E](https://user-images.githubusercontent.com/12766732/88318410-ea59a580-ccd7-11ea-81f5-034c6070a299.jpeg)
![EB8FDE1A-AE73-423E-B119-F2BDF79232D1](https://user-images.githubusercontent.com/12766732/88318424-eded2c80-ccd7-11ea-9a18-3c19778c2031.jpeg)

**Comment by JoanJetson** [comment]
Going through the git history for the Volcan.msav, previous versions have an error about not being able to read block type swarmer when trying to import them. Probably an asset that had been removed in a previous version but also probably worth mentioning.

**Comment by Mesokrix** [comment]
script don't work on iso...
