### ISSUE TITLE
Mat and pipe do not work

### ISSUE THREAD

**Issue by AstronautCat380** [Mesokrix/Vanilla-Upgraded#8]
treadmill and pipe do not work on the treadmill and the pipe that the mod adds does not work, please ask to fix this bug.

**Comment by Mesokrix** [comment]
its work now

**Comment by AstronautCat380** [comment]
thank you so much for tidying up. today I installed it again and the bug
was gone.
Suggestion: add a version of the aerial arc, only terrestrial.

Em sáb, 15 de ago de 2020 21:01, Mesokrix <notifications@github.com>
escreveu:
